use std::collections::HashMap;

use genegis_geometry::BoundingBox;

use crate::dataset::{DatasetFormat, DatasetRecord};
use crate::error::CatalogError;

/// Well-known dataset id for the Nagoya north-star demo.
pub const NAGOYA_WARDS_DENSITY_ID: &str = "nagoya-wards-density";

/// Well-known dataset id for the remote COG metadata demo.
pub const REMOTE_COG_DEMO_ID: &str = "remote-cog-demo";

/// Well-known dataset id for the bundled local COG metadata demo.
pub const LOCAL_COG_DEMO_ID: &str = "local-cog-demo";

/// Well-known dataset id for the bundled Nagoya wards GeoParquet asset.
pub const NAGOYA_WARDS_GEOPARQUET_ID: &str = "nagoya-wards-geoparquet";

/// Well-known dataset id for the external STAC collection demo.
pub const EXTERNAL_STAC_DEMO_ID: &str = "external-stac-demo";

/// Well-known dataset id for the synthetic flood inundation fixture (UC-1).
pub const NAGOYA_FLOOD_ZONES_ID: &str = "nagoya-flood-zones";

/// Well-known dataset id for the synthetic walk-network fixture (UC-4).
pub const NAGOYA_WALK_NETWORK_ID: &str = "nagoya-walk-network";

/// Well-known dataset id for the synthetic POI fixture (UC-4).
pub const NAGOYA_POIS_ID: &str = "nagoya-pois";

/// Well-known dataset id for the synthetic evacuation-shelter fixture (UC-1).
pub const NAGOYA_SHELTERS_ID: &str = "nagoya-shelters";

/// Well-known dataset id for the synthetic NDVI time-series STAC fixture (UC-3).
pub const SENTINEL_NDVI_DEMO_ID: &str = "sentinel-ndvi-demo";

/// Well-known dataset id for the two-epoch change-detection fixture (UC-5).
pub const POINTCLOUD_CHANGE_ID: &str = "pointcloud-change-demo";

/// Path to the bundled Nagoya wards GeoJSON asset.
pub fn nagoya_wards_geojson_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-wards.geojson"
    )
}

/// Path to the bundled synthetic flood inundation zones fixture.
///
/// Set `GENEGIS_FLOOD_ZONES_PATH` (and `GENEGIS_FLOOD_ZONES_SHA`) to run the
/// same workflows on real data, e.g. the A31a layer produced by
/// `scripts/fetch-real-data.py`. Checksums must be re-declared alongside the
/// path so receipts stay fail-closed.
pub fn nagoya_flood_zones_path() -> &'static str {
    if let Ok(path) = std::env::var("GENEGIS_FLOOD_ZONES_PATH") {
        return Box::leak(path.into_boxed_str());
    }
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-flood-zones.geojson"
    )
}

fn declared_checksum(env_key: &str, fixture: &str) -> String {
    format!(
        "sha256:{}",
        std::env::var(env_key).unwrap_or_else(|_| fixture.to_string())
    )
}

/// Path to the bundled walk-network fixture.
pub fn nagoya_walk_network_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-walk-network.geojson"
    )
}

/// Path to the bundled POI fixture.
pub fn nagoya_pois_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-pois.geojson"
    )
}

/// Path to the bundled evacuation-shelter fixture.
///
/// Set `GENEGIS_SHELTERS_PATH` (and `GENEGIS_SHELTERS_SHA`) to run on real
/// shelter data, e.g. the 名古屋市指定避難所 conversion produced by
/// `scripts/fetch-real-data.py`.
pub fn nagoya_shelters_path() -> &'static str {
    if let Ok(path) = std::env::var("GENEGIS_SHELTERS_PATH") {
        return Box::leak(path.into_boxed_str());
    }
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-shelters.geojson"
    )
}

/// Path to the change-detection epoch A point cloud (UC-5).
pub fn nagoya_pointcloud_epoch_a_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-change-epoch-a.las"
    )
}

/// Path to the change-detection epoch B point cloud (UC-5).
pub fn nagoya_pointcloud_epoch_b_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-change-epoch-b.las"
    )
}

/// Path to the bundled Nagoya wards GeoParquet asset (generated by CI / example).
pub fn nagoya_wards_geoparquet_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-wards.parquet"
    )
}

/// Repository root for fixture resolution in tests and CLI.
pub fn repo_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// In-memory dataset registry (Phase 2 alpha).
#[derive(Debug, Clone, Default)]
pub struct Catalog {
    datasets: HashMap<String, DatasetRecord>,
}

impl Catalog {
    pub fn new() -> Self {
        Self {
            datasets: HashMap::new(),
        }
    }

    pub fn register(&mut self, record: DatasetRecord) {
        self.datasets.insert(record.id.clone(), record);
    }

    pub fn get(&self, id: &str) -> Option<&DatasetRecord> {
        self.datasets.get(id)
    }

    pub fn require(&self, id: &str) -> Result<&DatasetRecord, CatalogError> {
        self.get(id)
            .ok_or_else(|| CatalogError::NotFound(id.to_string()))
    }

    pub fn list(&self) -> Vec<&DatasetRecord> {
        let mut records: Vec<_> = self.datasets.values().collect();
        records.sort_by(|a, b| a.id.cmp(&b.id));
        records
    }
}

/// Default alpha catalog — Nagoya wards population density (GeoJSON + GeoParquet-ready).
pub fn alpha_catalog() -> Catalog {
    let mut catalog = Catalog::new();
    catalog.register(nagoya_wards_density_record());
    catalog.register(remote_cog_demo_record());
    catalog.register(local_cog_demo_record());
    catalog.register(nagoya_geoparquet_record());
    catalog.register(external_stac_demo_record());
    catalog.register(nagoya_flood_zones_record());
    catalog.register(nagoya_walk_network_record());
    catalog.register(nagoya_pois_record());
    catalog.register(nagoya_shelters_record());
    catalog.register(sentinel_ndvi_demo_record());
    catalog.register(pointcloud_change_record());
    catalog
}

/// Alpha catalog merged with imported STAC overlay records.
pub fn extended_catalog() -> Catalog {
    let mut catalog = alpha_catalog();
    for record in crate::external_stac::load_catalog_overlay() {
        catalog.register(record);
    }
    catalog
}

/// Synthetic flood inundation fixture for the UC-1 exposure overlay.
fn nagoya_flood_zones_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_FLOOD_ZONES_ID.into(),
        title: "Nagoya synthetic flood inundation zones (depth bands)".into(),
        description: "Offline demo fixture approximating 想定最大規模 river-corridor and coastal inundation depth bands over Nagoya. Generated by scripts/build-nagoya-flood-zones.py; not survey data.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.842, 35.048, 136.971, 35.221),
        uri: nagoya_flood_zones_path().into(),
        license: "CC0-1.0 (synthetic fixture; 参考: 国土数値情報 A32 / ハザードマップポータルサイト)".into(),
        checksum: Some(declared_checksum(
            "GENEGIS_FLOOD_ZONES_SHA",
            "3d3fa3c7511cce237b3be186b63207760828b85c0e5377819ecf275b06790700",
        )),
        source_version: Some("nagoya-flood-fixture-v1".into()),
        tags: vec!["nagoya".into(), "flood".into(), "hazard".into(), "demo".into()],
    }
}

fn nagoya_walk_network_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_WALK_NETWORK_ID.into(),
        title: "Nagoya synthetic walk network (~400m grid)".into(),
        description: "Planning-level walking grid over the Nagoya bbox generated by scripts/build-nagoya-walk-network.py; not OSM survey geometry.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.785, 35.025, 137.068, 35.268),
        uri: nagoya_walk_network_path().into(),
        license: "CC0-1.0 (synthetic fixture; 参考: OpenStreetMap walkers' spacing conventions)".into(),
        checksum: Some(
            "sha256:5e7e942f5c90382cb4e3a7861d2c792c5806d2fac168be53ef42193e9e1da20e".into(),
        ),
        source_version: Some("nagoya-walk-grid-v1".into()),
        tags: vec!["nagoya".into(), "walk".into(), "network".into(), "demo".into()],
    }
}

fn nagoya_pois_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_POIS_ID.into(),
        title: "Nagoya synthetic POIs by category".into(),
        description: "Deterministic POI fixtures near ward centroids (supermarket/clinic/school/park) for the 15-minute-city demo.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.855, 35.080, 136.995, 35.235),
        uri: nagoya_pois_path().into(),
        license: "CC0-1.0 (synthetic fixture)".into(),
        checksum: Some(
            "sha256:193327ce0c6d6a8c578325a748d693d4e9488ae2ec02b1dbdd5bd4c7d42e8c30".into(),
        ),
        source_version: Some("nagoya-poi-fixture-v1".into()),
        tags: vec!["nagoya".into(), "poi".into(), "walkability".into(), "demo".into()],
    }
}

fn nagoya_shelters_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_SHELTERS_ID.into(),
        title: "Nagoya synthetic evacuation shelters (2 per ward)".into(),
        description: "Deterministic designated-evacuation-shelter fixtures placed outside bundled flood zones. Generated by scripts/build-nagoya-shelters.py; 参考: GSI 指定避難所データ構造.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: nagoya_shelters_path().into(),
        license: "CC0-1.0 (synthetic fixture; 参考: 国土地理院 指定緊急避難場所・指定避難所)".into(),
        checksum: Some(declared_checksum(
            "GENEGIS_SHELTERS_SHA",
            "696f9aad022cf498cfb1d01466c53f654541bb5f7077816fe6159921e1da5145",
        )),
        source_version: Some("nagoya-shelter-fixture-v1".into()),
        tags: vec!["nagoya".into(), "shelter".into(), "evacuation".into(), "demo".into()],
    }
}

fn sentinel_ndvi_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: SENTINEL_NDVI_DEMO_ID.into(),
        title: "Nagoya NDVI time series — Sentinel-2-like synthetic COGs".into(),
        description: "Two-epoch vegetation index fixture discovered via a bundled STAC Collection. Rasters generated by crates/genegis-raster/examples/write_ndvi_fixture.rs; not real Sentinel-2 data.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.79, 35.03, 137.07, 35.27),
        uri: concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../examples/stac/ndvi-timeseries-collection.json"
        )
        .into(),
        license: "CC0-1.0 (synthetic fixture)".into(),
        checksum: Some(
            "sha256:7317e35f12a6332fd23eb8f916426c7018e7722b04d0d1d0a752eb9971119a65".into(),
        ),
        source_version: Some("nagoya-ndvi-fixture-v1".into()),
        tags: vec!["ndvi".into(), "sentinel".into(), "timeseries".into(), "demo".into()],
    }
}

fn pointcloud_change_record() -> DatasetRecord {
    DatasetRecord {
        id: POINTCLOUD_CHANGE_ID.into(),
        title: "Nagoya synthetic LiDAR epochs A/B (change detection)".into(),
        description: "Two deterministic uncompressed LAS epochs over a 600m x 400m local-planar AOI with known added/removed building, grown/cleared vegetation and an unchanged control quadrant. Generated by crates/genegis-pointcloud/examples/write_change_fixture.rs; not GSI survey data.".into(),
        format: DatasetFormat::las(),
        crs: "EPSG:6675".into(),
        bbox: BoundingBox::new(0.0, 0.0, 600.0, 400.0),
        uri: nagoya_pointcloud_epoch_a_path().into(),
        license: "CC0-1.0 (synthetic fixture; 参考: 国土地理院空中点群)".into(),
        checksum: Some(
            "sha256:2b02cb917ce76e481d9c013feb47d76138b3b60e605bad017fed14a97babc6d6".into(),
        ),
        source_version: Some("nagoya-change-fixture-v1".into()),
        tags: vec!["pointcloud".into(), "change".into(), "demo".into()],
    }
}

fn nagoya_wards_density_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_WARDS_DENSITY_ID.into(),
        title: "Nagoya city wards — population density".into(),
        description: "16 Nagoya wards with the 2020 Nagoya City census final population, N03-derived boundaries, and an immutable source/oracle manifest.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: nagoya_wards_geojson_path().into(),
        license: "名古屋市オープンデータ利用規約（政府標準利用規約2.0準拠） + MLIT N03 政府標準利用規約".into(),
        checksum: Some(
            "sha256:d0f8958813fe28e9428169ca7c638a0ea3b3ed7ae526750156d3f94e1308d30e".into(),
        ),
        source_version: Some("nagoya-2020-census-final-n03-v2".into()),
        tags: vec![
            "nagoya".into(),
            "population".into(),
            "density".into(),
            "wards".into(),
        ],
    }
}

fn remote_cog_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: REMOTE_COG_DEMO_ID.into(),
        title: "Remote GeoTIFF / COG metadata demo".into(),
        description:
            "Public OSGeo GeoTIFF sample for HTTP range-read and raster metadata smoke tests."
                .into(),
        format: DatasetFormat::cog(),
        crs: "EPSG:32617".into(),
        bbox: BoundingBox::new(-78.638, 40.983, -78.487, 41.129),
        uri: "http://download.osgeo.org/geotiff/samples/usgs/o41078a5.tif".into(),
        license: "Public domain (OSGeo sample data)".into(),
        checksum: None,
        source_version: Some("osgeo-usgs-sample-v1".into()),
        tags: vec![
            "cog".into(),
            "remote".into(),
            "demo".into(),
            "raster".into(),
        ],
    }
}

fn nagoya_geoparquet_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_WARDS_GEOPARQUET_ID.into(),
        title: "Nagoya city wards — GeoParquet fixture".into(),
        description: "16 Nagoya wards exported to GeoParquet for offline vector verification."
            .into(),
        format: DatasetFormat::geoparquet(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: nagoya_wards_geoparquet_path().into(),
        license:
            "名古屋市オープンデータ利用規約（政府標準利用規約2.0準拠） + MLIT N03 政府標準利用規約"
                .into(),
        checksum: None,
        source_version: Some("nagoya-2020-census-final-n03-geoparquet-v2".into()),
        tags: vec![
            "nagoya".into(),
            "geoparquet".into(),
            "density".into(),
            "wards".into(),
            "demo".into(),
        ],
    }
}

fn external_stac_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: EXTERNAL_STAC_DEMO_ID.into(),
        title: "External STAC collection demo".into(),
        description: "Bundled sample STAC Collection JSON for offline fetch/import smoke tests."
            .into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../examples/stac/sample-collection.json"
        )
        .into(),
        license: "CC-BY-4.0".into(),
        checksum: Some(
            "sha256:396e617f60ed11a041281ce55bd257aedf22ae1d1e269f9035468b61116fb994".into(),
        ),
        source_version: Some("sample-stac-collection-v1".into()),
        tags: vec!["stac".into(), "external".into(), "demo".into()],
    }
}

fn local_cog_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: LOCAL_COG_DEMO_ID.into(),
        title: "Local bundled COG metadata demo".into(),
        description: "Offline smoke GeoTIFF generated at build time for local COG workflows."
            .into(),
        format: DatasetFormat::cog(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(-180.0, 89.52, -179.36, 90.0),
        uri: genegis_raster::smoke_demo_cog_path().into(),
        license: "GeneGIS smoke fixture".into(),
        checksum: None,
        source_version: Some("gene-gis-smoke-cog-v1".into()),
        tags: vec!["cog".into(), "local".into(), "demo".into(), "raster".into()],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn alpha_catalog_lists_nagoya_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(NAGOYA_WARDS_DENSITY_ID).expect("record");
        assert_eq!(record.format.kind, "geojson");
        assert_eq!(record.coordinate_unit().as_str(), "degrees");
        assert_eq!(record.parsed_crs().expect("crs").identifier(), "EPSG:4326");
        let source = record.source_metadata();
        assert_eq!(source.checksum_status.as_str(), "verified");
        assert_eq!(
            source.source_version.as_ref().map(|v| v.as_str()),
            Some("nagoya-2020-census-final-n03-v2")
        );
        assert_eq!(record.summary_json()["checksum_status"], "verified");
        assert_eq!(
            record.summary_json()["expected_checksum"],
            record.summary_json()["observed_checksum"]
        );
        assert!(std::path::Path::new(&record.uri).exists());
    }

    #[test]
    fn alpha_catalog_lists_remote_cog_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(REMOTE_COG_DEMO_ID).expect("record");
        assert_eq!(record.format.kind, "cog");
        assert!(genegis_storage::is_remote_uri(&record.uri));
        assert_eq!(record.source_metadata().checksum_status.as_str(), "unknown");
        assert_eq!(catalog.list().len(), 11);
    }

    #[test]
    fn alpha_catalog_lists_local_cog_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(LOCAL_COG_DEMO_ID).expect("record");
        assert_eq!(record.format.kind, "cog");
        assert!(std::path::Path::new(&record.uri).exists());
    }

    #[test]
    fn alpha_catalog_lists_geoparquet_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(NAGOYA_WARDS_GEOPARQUET_ID).expect("record");
        assert_eq!(record.format.kind, "geoparquet");
        assert!(std::path::Path::new(&record.uri).exists());
    }
}
