use std::collections::HashMap;

use genegis_geometry::BoundingBox;

use crate::dataset::{DatasetFormat, DatasetRecord};
use crate::error::CatalogError;

/// Well-known dataset id for the Nagoya north-star demo.
pub const NAGOYA_WARDS_DENSITY_ID: &str = "nagoya-wards-density";

/// Well-known dataset id for the remote COG metadata demo.
pub const REMOTE_COG_DEMO_ID: &str = "remote-cog-demo";

/// Well-known dataset id for the bundled local COG metadata demo.
pub const LOCAL_COG_DEMO_ID: &str = "local-cog-demo";

/// Well-known dataset id for the bundled Nagoya wards GeoParquet asset.
pub const NAGOYA_WARDS_GEOPARQUET_ID: &str = "nagoya-wards-geoparquet";

/// Well-known dataset id for the external STAC collection demo.
pub const EXTERNAL_STAC_DEMO_ID: &str = "external-stac-demo";

/// Path to the bundled Nagoya wards GeoJSON asset.
pub fn nagoya_wards_geojson_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-wards.geojson"
    )
}

/// Path to the bundled Nagoya wards GeoParquet asset (generated by CI / example).
pub fn nagoya_wards_geoparquet_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-wards.parquet"
    )
}

/// Repository root for fixture resolution in tests and CLI.
pub fn repo_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// In-memory dataset registry (Phase 2 alpha).
#[derive(Debug, Clone, Default)]
pub struct Catalog {
    datasets: HashMap<String, DatasetRecord>,
}

impl Catalog {
    pub fn new() -> Self {
        Self {
            datasets: HashMap::new(),
        }
    }

    pub fn register(&mut self, record: DatasetRecord) {
        self.datasets.insert(record.id.clone(), record);
    }

    pub fn get(&self, id: &str) -> Option<&DatasetRecord> {
        self.datasets.get(id)
    }

    pub fn require(&self, id: &str) -> Result<&DatasetRecord, CatalogError> {
        self.get(id)
            .ok_or_else(|| CatalogError::NotFound(id.to_string()))
    }

    pub fn list(&self) -> Vec<&DatasetRecord> {
        let mut records: Vec<_> = self.datasets.values().collect();
        records.sort_by(|a, b| a.id.cmp(&b.id));
        records
    }
}

/// Default alpha catalog — Nagoya wards population density (GeoJSON + GeoParquet-ready).
pub fn alpha_catalog() -> Catalog {
    let mut catalog = Catalog::new();
    catalog.register(nagoya_wards_density_record());
    catalog.register(remote_cog_demo_record());
    catalog.register(local_cog_demo_record());
    catalog.register(nagoya_geoparquet_record());
    catalog.register(external_stac_demo_record());
    catalog
}

/// Alpha catalog merged with imported STAC overlay records.
pub fn extended_catalog() -> Catalog {
    let mut catalog = alpha_catalog();
    for record in crate::external_stac::load_catalog_overlay() {
        catalog.register(record);
    }
    catalog
}

fn nagoya_wards_density_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_WARDS_DENSITY_ID.into(),
        title: "Nagoya city wards — population density".into(),
        description: "16 Nagoya wards with the 2020 Nagoya City census final population, N03-derived boundaries, and an immutable source/oracle manifest.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: nagoya_wards_geojson_path().into(),
        license: "名古屋市オープンデータ利用規約（政府標準利用規約2.0準拠） + MLIT N03 政府標準利用規約".into(),
        checksum: Some(
            "sha256:d0f8958813fe28e9428169ca7c638a0ea3b3ed7ae526750156d3f94e1308d30e".into(),
        ),
        source_version: Some("nagoya-2020-census-final-n03-v2".into()),
        tags: vec![
            "nagoya".into(),
            "population".into(),
            "density".into(),
            "wards".into(),
        ],
    }
}

fn remote_cog_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: REMOTE_COG_DEMO_ID.into(),
        title: "Remote GeoTIFF / COG metadata demo".into(),
        description:
            "Public OSGeo GeoTIFF sample for HTTP range-read and raster metadata smoke tests."
                .into(),
        format: DatasetFormat::cog(),
        crs: "EPSG:32617".into(),
        bbox: BoundingBox::new(-78.638, 40.983, -78.487, 41.129),
        uri: "http://download.osgeo.org/geotiff/samples/usgs/o41078a5.tif".into(),
        license: "Public domain (OSGeo sample data)".into(),
        checksum: None,
        source_version: Some("osgeo-usgs-sample-v1".into()),
        tags: vec![
            "cog".into(),
            "remote".into(),
            "demo".into(),
            "raster".into(),
        ],
    }
}

fn nagoya_geoparquet_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_WARDS_GEOPARQUET_ID.into(),
        title: "Nagoya city wards — GeoParquet fixture".into(),
        description: "16 Nagoya wards exported to GeoParquet for offline vector verification."
            .into(),
        format: DatasetFormat::geoparquet(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: nagoya_wards_geoparquet_path().into(),
        license:
            "名古屋市オープンデータ利用規約（政府標準利用規約2.0準拠） + MLIT N03 政府標準利用規約"
                .into(),
        checksum: None,
        source_version: Some("nagoya-2020-census-final-n03-geoparquet-v2".into()),
        tags: vec![
            "nagoya".into(),
            "geoparquet".into(),
            "density".into(),
            "wards".into(),
            "demo".into(),
        ],
    }
}

fn external_stac_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: EXTERNAL_STAC_DEMO_ID.into(),
        title: "External STAC collection demo".into(),
        description: "Bundled sample STAC Collection JSON for offline fetch/import smoke tests."
            .into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../examples/stac/sample-collection.json"
        )
        .into(),
        license: "CC-BY-4.0".into(),
        checksum: Some(
            "sha256:396e617f60ed11a041281ce55bd257aedf22ae1d1e269f9035468b61116fb994".into(),
        ),
        source_version: Some("sample-stac-collection-v1".into()),
        tags: vec!["stac".into(), "external".into(), "demo".into()],
    }
}

fn local_cog_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: LOCAL_COG_DEMO_ID.into(),
        title: "Local bundled COG metadata demo".into(),
        description: "Offline smoke GeoTIFF generated at build time for local COG workflows."
            .into(),
        format: DatasetFormat::cog(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(-180.0, 89.52, -179.36, 90.0),
        uri: genegis_raster::smoke_demo_cog_path().into(),
        license: "GeneGIS smoke fixture".into(),
        checksum: None,
        source_version: Some("gene-gis-smoke-cog-v1".into()),
        tags: vec!["cog".into(), "local".into(), "demo".into(), "raster".into()],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn alpha_catalog_lists_nagoya_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(NAGOYA_WARDS_DENSITY_ID).expect("record");
        assert_eq!(record.format.kind, "geojson");
        assert_eq!(record.coordinate_unit().as_str(), "degrees");
        assert_eq!(record.parsed_crs().expect("crs").identifier(), "EPSG:4326");
        let source = record.source_metadata();
        assert_eq!(source.checksum_status.as_str(), "verified");
        assert_eq!(
            source.source_version.as_ref().map(|v| v.as_str()),
            Some("nagoya-2020-census-final-n03-v2")
        );
        assert_eq!(record.summary_json()["checksum_status"], "verified");
        assert_eq!(
            record.summary_json()["expected_checksum"],
            record.summary_json()["observed_checksum"]
        );
        assert!(std::path::Path::new(&record.uri).exists());
    }

    #[test]
    fn alpha_catalog_lists_remote_cog_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(REMOTE_COG_DEMO_ID).expect("record");
        assert_eq!(record.format.kind, "cog");
        assert!(genegis_storage::is_remote_uri(&record.uri));
        assert_eq!(record.source_metadata().checksum_status.as_str(), "unknown");
        assert_eq!(catalog.list().len(), 5);
    }

    #[test]
    fn alpha_catalog_lists_local_cog_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(LOCAL_COG_DEMO_ID).expect("record");
        assert_eq!(record.format.kind, "cog");
        assert!(std::path::Path::new(&record.uri).exists());
    }

    #[test]
    fn alpha_catalog_lists_geoparquet_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(NAGOYA_WARDS_GEOPARQUET_ID).expect("record");
        assert_eq!(record.format.kind, "geoparquet");
        assert!(std::path::Path::new(&record.uri).exists());
    }
}
