use std::collections::HashMap;

use genegis_geometry::BoundingBox;

use crate::dataset::{DatasetFormat, DatasetRecord};
use crate::error::CatalogError;

/// Well-known dataset id for the Nagoya north-star demo.
pub const NAGOYA_WARDS_DENSITY_ID: &str = "nagoya-wards-density";

/// Well-known dataset id for the remote COG metadata demo.
pub const REMOTE_COG_DEMO_ID: &str = "remote-cog-demo";

/// Well-known dataset id for the bundled local COG metadata demo.
pub const LOCAL_COG_DEMO_ID: &str = "local-cog-demo";

/// Well-known dataset id for the bundled Nagoya wards GeoParquet asset.
pub const NAGOYA_WARDS_GEOPARQUET_ID: &str = "nagoya-wards-geoparquet";

/// Path to the bundled Nagoya wards GeoJSON asset.
pub fn nagoya_wards_geojson_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-wards.geojson"
    )
}

/// Path to the bundled Nagoya wards GeoParquet asset (generated by CI / example).
pub fn nagoya_wards_geoparquet_path() -> &'static str {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../examples/nagoya-population-density/data/nagoya-wards.parquet"
    )
}

/// Repository root for fixture resolution in tests and CLI.
pub fn repo_root() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..")
}

/// In-memory dataset registry (Phase 2 alpha).
#[derive(Debug, Clone, Default)]
pub struct Catalog {
    datasets: HashMap<String, DatasetRecord>,
}

impl Catalog {
    pub fn new() -> Self {
        Self {
            datasets: HashMap::new(),
        }
    }

    pub fn register(&mut self, record: DatasetRecord) {
        self.datasets.insert(record.id.clone(), record);
    }

    pub fn get(&self, id: &str) -> Option<&DatasetRecord> {
        self.datasets.get(id)
    }

    pub fn require(&self, id: &str) -> Result<&DatasetRecord, CatalogError> {
        self.get(id)
            .ok_or_else(|| CatalogError::NotFound(id.to_string()))
    }

    pub fn list(&self) -> Vec<&DatasetRecord> {
        let mut records: Vec<_> = self.datasets.values().collect();
        records.sort_by(|a, b| a.id.cmp(&b.id));
        records
    }
}

/// Default alpha catalog — Nagoya wards population density (GeoJSON + GeoParquet-ready).
pub fn alpha_catalog() -> Catalog {
    let mut catalog = Catalog::new();
    catalog.register(nagoya_wards_density_record());
    catalog.register(remote_cog_demo_record());
    catalog.register(local_cog_demo_record());
    catalog.register(nagoya_geoparquet_record());
    catalog
}

/// Alpha catalog merged with imported STAC overlay records.
pub fn extended_catalog() -> Catalog {
    let mut catalog = alpha_catalog();
    for record in crate::external_stac::load_catalog_overlay() {
        catalog.register(record);
    }
    catalog
}

fn nagoya_wards_density_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_WARDS_DENSITY_ID.into(),
        title: "Nagoya city wards — population density".into(),
        description: "16 Nagoya wards with 2020 census population and N03-derived boundaries.".into(),
        format: DatasetFormat::geojson(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: nagoya_wards_geojson_path().into(),
        license: "Government open data (Japan) + MLIT N03".into(),
        tags: vec![
            "nagoya".into(),
            "population".into(),
            "density".into(),
            "wards".into(),
        ],
    }
}

fn remote_cog_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: REMOTE_COG_DEMO_ID.into(),
        title: "Remote GeoTIFF / COG metadata demo".into(),
        description: "Public OSGeo GeoTIFF sample for HTTP range-read and raster metadata smoke tests."
            .into(),
        format: DatasetFormat::cog(),
        crs: "EPSG:26718".into(),
        bbox: BoundingBox::new(-79.05, 42.02, -78.98, 42.08),
        uri: "https://download.osgeo.org/geotiff/samples/gcp.tif".into(),
        license: "Public domain (OSGeo sample data)".into(),
        tags: vec![
            "cog".into(),
            "remote".into(),
            "demo".into(),
            "raster".into(),
        ],
    }
}

fn nagoya_geoparquet_record() -> DatasetRecord {
    DatasetRecord {
        id: NAGOYA_WARDS_GEOPARQUET_ID.into(),
        title: "Nagoya city wards — GeoParquet fixture".into(),
        description: "16 Nagoya wards exported to GeoParquet for offline vector verification.".into(),
        format: DatasetFormat::geoparquet(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(136.792, 35.034, 137.061, 35.260),
        uri: nagoya_wards_geoparquet_path().into(),
        license: "Government open data (Japan) + MLIT N03".into(),
        tags: vec![
            "nagoya".into(),
            "geoparquet".into(),
            "wards".into(),
            "demo".into(),
        ],
    }
}

fn local_cog_demo_record() -> DatasetRecord {
    DatasetRecord {
        id: LOCAL_COG_DEMO_ID.into(),
        title: "Local bundled COG metadata demo".into(),
        description: "Offline smoke GeoTIFF generated at build time for local COG workflows.".into(),
        format: DatasetFormat::cog(),
        crs: "EPSG:4326".into(),
        bbox: BoundingBox::new(-180.0, 89.52, -179.36, 90.0),
        uri: genegis_raster::smoke_demo_cog_path().into(),
        license: "GeneGIS smoke fixture".into(),
        tags: vec![
            "cog".into(),
            "local".into(),
            "demo".into(),
            "raster".into(),
        ],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn alpha_catalog_lists_nagoya_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(NAGOYA_WARDS_DENSITY_ID).expect("record");
        assert_eq!(record.format.kind, "geojson");
        assert!(std::path::Path::new(&record.uri).exists());
    }

    #[test]
    fn alpha_catalog_lists_remote_cog_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(REMOTE_COG_DEMO_ID).expect("record");
        assert_eq!(record.format.kind, "cog");
        assert!(record.uri.starts_with("https://"));
        assert_eq!(catalog.list().len(), 4);
    }

    #[test]
    fn alpha_catalog_lists_local_cog_demo() {
        let catalog = alpha_catalog();
        let record = catalog.require(LOCAL_COG_DEMO_ID).expect("record");
        assert_eq!(record.format.kind, "cog");
        assert!(std::path::Path::new(&record.uri).exists());
    }

    #[test]
    fn alpha_catalog_lists_geoparquet_demo() {
        let catalog = alpha_catalog();
        let record = catalog
            .require(NAGOYA_WARDS_GEOPARQUET_ID)
            .expect("record");
        assert_eq!(record.format.kind, "geoparquet");
        assert!(std::path::Path::new(&record.uri).exists());
    }
}
