//! Allowlisted, digest-bound portable viewer export from a verified result capsule.

use std::{
    fs,
    path::{Path, PathBuf},
};

use base64::{engine::general_purpose::STANDARD as BASE64, Engine};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{verify_nagoya_capsule, CapsuleError, CapsuleManifest};

/// Portable publication schema version.
pub const PUBLICATION_SCHEMA_VERSION: &str = "0.1.0";

/// Explicit allowlist/redaction policy bound into every publication digest.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PublicationPolicy {
    /// Include the independently verifiable capsule as a relative download.
    pub include_capsule_download: bool,
    /// Reject local paths in public HTML and metadata.
    pub reject_local_paths: bool,
    /// Public field classes emitted by the exporter.
    pub included_field_classes: Vec<String>,
    /// Sensitive field classes omitted by construction.
    pub redacted_field_classes: Vec<String>,
}

impl Default for PublicationPolicy {
    fn default() -> Self {
        Self {
            include_capsule_download: true,
            reject_local_paths: true,
            included_field_classes: vec![
                "title_and_description".into(),
                "attribution_and_license".into(),
                "limitations".into(),
                "verification_state".into(),
                "crs_and_units".into(),
                "content_digests".into(),
                "portable_artifact_paths".into(),
            ],
            redacted_field_classes: vec![
                "local_filesystem_paths".into(),
                "credentials_and_environment".into(),
                "reviewer_identities_and_comments".into(),
                "prompt_and_arbitrary_provenance_details".into(),
            ],
        }
    }
}

/// Public source credit retained without private source paths.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PublicationAttribution {
    /// Source or publication title.
    pub title: String,
    /// Public source URL.
    pub url: String,
    /// License or attribution terms.
    pub license: String,
}

/// Hash of one generated public file.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PublicationFileEntry {
    /// Portable relative path.
    pub path: String,
    /// SHA-256 of exact generated bytes.
    pub sha256: String,
    /// Exact generated byte length.
    pub bytes: u64,
}

/// Allowlisted metadata shared by the full and embedded viewers.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PortablePublication {
    /// Publication schema version.
    pub schema_version: String,
    /// Human-readable result title.
    pub title: String,
    /// Fixed description of the exported review view.
    pub description: String,
    /// Public source credits.
    pub attribution: Vec<PublicationAttribution>,
    /// Declared workflow assumptions and limitations.
    pub limitations: Vec<String>,
    /// CRS serialized from the verified execution receipt.
    pub crs: serde_json::Value,
    /// Coordinate unit from the verified execution receipt.
    pub coordinate_unit: String,
    /// Offline-derived trust level.
    pub trust_level: serde_json::Value,
    /// Verified result identity.
    pub result_digest: String,
    /// Workflow Graph identity.
    pub workflow_digest: String,
    /// Verification graph identity.
    pub verification_graph_digest: String,
    /// Verification-policy bytes identity.
    pub verification_policy_digest: String,
    /// Source capsule manifest identity.
    pub capsule_digest: String,
    /// Relative source capsule path when downloads are enabled.
    pub capsule_download: Option<String>,
    /// Relative full review view.
    pub share_path: String,
    /// Relative minimal embed view.
    pub embed_path: String,
    /// Explicit redaction contract.
    pub policy: PublicationPolicy,
    /// Canonical semantic publication identity.
    pub publication_digest: String,
    /// Generated file hashes, excluded from semantic digest to avoid cycles.
    pub public_entries: Vec<PublicationFileEntry>,
}

/// Successful offline verification of a publication and source capsule.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PublicationVerification {
    /// Verified publication identity.
    pub publication_digest: String,
    /// Verified analytical result identity.
    pub result_digest: String,
    /// Number of public files checked.
    pub verified_public_entries: usize,
    /// Number of source capsule entries checked.
    pub verified_capsule_entries: usize,
}

/// Export full and embedded static viewers from an offline-verified capsule.
pub fn export_portable_publication(
    capsule_root: impl AsRef<Path>,
    output_root: impl AsRef<Path>,
    policy: &PublicationPolicy,
) -> Result<PortablePublication, CapsuleError> {
    validate_policy(policy)?;
    let capsule_root = capsule_root.as_ref();
    let output_root = output_root.as_ref();
    let verified = verify_nagoya_capsule(capsule_root, None)?;
    ensure_empty_destination(output_root)?;
    fs::create_dir_all(output_root).map_err(|source| io_error(output_root, source))?;

    let capsule_bytes = read_bytes(&capsule_root.join("capsule.json"))?;
    let capsule_manifest: CapsuleManifest = serde_json::from_slice(&capsule_bytes)?;
    let analysis: serde_json::Value = read_json(&capsule_root.join("metadata/analysis.json"))?;
    let workflow: serde_json::Value = read_json(&capsule_root.join("metadata/workflow.json"))?;
    let receipt: serde_json::Value = read_json(&capsule_root.join("metadata/receipt.json"))?;
    let policy_bytes = read_bytes(&capsule_root.join("metadata/verification-policy.json"))?;
    let png = read_bytes(&capsule_root.join("artifacts/map.png"))?;

    let title = required_text(&workflow, "/goal", "workflow goal")?.to_string();
    let attribution = parse_attribution(&analysis)?;
    let limitations = required_text_array(&workflow, "/assumptions", "workflow assumptions")?;
    let workflow_digest =
        required_text(&receipt, "/workflow_digest", "workflow digest")?.to_string();
    let coordinate_unit =
        required_text(&receipt, "/coordinate_unit", "coordinate unit")?.to_string();
    let crs = receipt
        .pointer("/crs")
        .filter(|value| !value.is_null())
        .cloned()
        .ok_or_else(|| verify_error("publication receipt has no CRS"))?;
    let trust_level = serde_json::to_value(&verified.trust)?
        .pointer("/level")
        .cloned()
        .ok_or_else(|| verify_error("publication has no derived trust level"))?;
    let mut publication = PortablePublication {
        schema_version: PUBLICATION_SCHEMA_VERSION.into(),
        title,
        description: "Verified, portable spatial result with downloadable offline evidence.".into(),
        attribution,
        limitations,
        crs,
        coordinate_unit,
        trust_level,
        result_digest: verified.result_digest.clone(),
        workflow_digest,
        verification_graph_digest: verified.verification_graph_digest,
        verification_policy_digest: sha256(&policy_bytes),
        capsule_digest: sha256(&capsule_bytes),
        capsule_download: policy
            .include_capsule_download
            .then(|| "capsule/capsule.json".into()),
        share_path: "index.html".into(),
        embed_path: "embed.html".into(),
        policy: policy.clone(),
        publication_digest: String::new(),
        public_entries: vec![],
    };
    publication.publication_digest = semantic_digest(&publication)?;
    let index = render_view(&publication, &png, false);
    let embed = render_view(&publication, &png, true);
    publication.public_entries = vec![
        write_public_file(output_root, "index.html", index.as_bytes())?,
        write_public_file(output_root, "embed.html", embed.as_bytes())?,
    ];
    fs::write(
        output_root.join("publication.json"),
        serde_json::to_vec_pretty(&publication)?,
    )
    .map_err(|source| io_error(&output_root.join("publication.json"), source))?;

    if policy.include_capsule_download {
        copy_capsule(capsule_root, output_root, &capsule_manifest)?;
    }
    verify_portable_publication(output_root)?;
    Ok(publication)
}

/// Verify generated files, allowlisted metadata, semantic digest, and source capsule.
pub fn verify_portable_publication(
    output_root: impl AsRef<Path>,
) -> Result<PublicationVerification, CapsuleError> {
    let output_root = output_root.as_ref();
    let publication_bytes = read_bytes(&output_root.join("publication.json"))?;
    let publication: PortablePublication = serde_json::from_slice(&publication_bytes)?;
    validate_policy(&publication.policy)?;
    if publication.schema_version != PUBLICATION_SCHEMA_VERSION
        || semantic_digest(&publication)? != publication.publication_digest
    {
        return Err(verify_error("publication semantic digest mismatch"));
    }
    if publication.attribution.is_empty() || publication.limitations.is_empty() {
        return Err(verify_error("publication lacks attribution or limitations"));
    }
    for entry in publication
        .public_entries
        .iter()
        .filter(|entry| entry.path != "publication.json")
    {
        validate_public_path(&entry.path)?;
        let bytes = read_bytes(&output_root.join(&entry.path))?;
        if entry.sha256 != sha256(&bytes) || entry.bytes != bytes.len() as u64 {
            return Err(verify_error(format!("public file changed: {}", entry.path)));
        }
        if publication.policy.reject_local_paths && contains_local_path(&bytes) {
            return Err(verify_error(format!(
                "public file leaks local path: {}",
                entry.path
            )));
        }
    }
    let public_json = serde_json::to_vec(&publication)?;
    if publication.policy.reject_local_paths && contains_local_path(&public_json) {
        return Err(verify_error("publication metadata leaks local path"));
    }
    let capsule_root = output_root.join("capsule");
    let capsule_manifest_bytes = read_bytes(&capsule_root.join("capsule.json"))?;
    if sha256(&capsule_manifest_bytes) != publication.capsule_digest {
        return Err(verify_error("downloadable capsule identity mismatch"));
    }
    let capsule = verify_nagoya_capsule(&capsule_root, None)?;
    if capsule.result_digest != publication.result_digest {
        return Err(verify_error(
            "publication and capsule result digests differ",
        ));
    }
    Ok(PublicationVerification {
        publication_digest: publication.publication_digest,
        result_digest: publication.result_digest,
        verified_public_entries: publication.public_entries.len(),
        verified_capsule_entries: capsule.verified_entries,
    })
}

fn parse_attribution(
    value: &serde_json::Value,
) -> Result<Vec<PublicationAttribution>, CapsuleError> {
    let citations = value
        .pointer("/citations")
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| verify_error("analysis has no attribution array"))?;
    let attribution = citations
        .iter()
        .map(|citation| {
            Ok(PublicationAttribution {
                title: required_text(citation, "/title", "citation title")?.into(),
                url: required_text(citation, "/url", "citation URL")?.into(),
                license: required_text(citation, "/license", "citation license")?.into(),
            })
        })
        .collect::<Result<Vec<_>, CapsuleError>>()?;
    if attribution.is_empty() {
        return Err(verify_error("publication requires attribution"));
    }
    Ok(attribution)
}

fn required_text<'a>(
    value: &'a serde_json::Value,
    pointer: &str,
    label: &str,
) -> Result<&'a str, CapsuleError> {
    value
        .pointer(pointer)
        .and_then(serde_json::Value::as_str)
        .filter(|text| !text.trim().is_empty())
        .ok_or_else(|| verify_error(format!("publication requires {label}")))
}

fn required_text_array(
    value: &serde_json::Value,
    pointer: &str,
    label: &str,
) -> Result<Vec<String>, CapsuleError> {
    let values = value
        .pointer(pointer)
        .and_then(serde_json::Value::as_array)
        .ok_or_else(|| verify_error(format!("publication requires {label}")))?
        .iter()
        .filter_map(serde_json::Value::as_str)
        .filter(|text| !text.trim().is_empty())
        .map(ToOwned::to_owned)
        .collect::<Vec<_>>();
    if values.is_empty() {
        return Err(verify_error(format!(
            "publication requires non-empty {label}"
        )));
    }
    Ok(values)
}

fn semantic_digest(publication: &PortablePublication) -> Result<String, CapsuleError> {
    let value = serde_json::json!({
        "schema_version": publication.schema_version,
        "title": publication.title,
        "description": publication.description,
        "attribution": publication.attribution,
        "limitations": publication.limitations,
        "crs": publication.crs,
        "coordinate_unit": publication.coordinate_unit,
        "trust_level": publication.trust_level,
        "result_digest": publication.result_digest,
        "workflow_digest": publication.workflow_digest,
        "verification_graph_digest": publication.verification_graph_digest,
        "verification_policy_digest": publication.verification_policy_digest,
        "capsule_digest": publication.capsule_digest,
        "capsule_download": publication.capsule_download,
        "share_path": publication.share_path,
        "embed_path": publication.embed_path,
        "policy": publication.policy,
    });
    Ok(sha256(&serde_json::to_vec(&value)?))
}

fn render_view(publication: &PortablePublication, png: &[u8], embed: bool) -> String {
    let credits = publication
        .attribution
        .iter()
        .map(|item| {
            format!(
                "<li><a href=\"{}\">{}</a> — {}</li>",
                escape(&item.url),
                escape(&item.title),
                escape(&item.license)
            )
        })
        .collect::<String>();
    let limitations = publication
        .limitations
        .iter()
        .map(|item| format!("<li>{}</li>", escape(item)))
        .collect::<String>();
    let evidence = if embed {
        format!(
            "<a href=\"index.html#{}\" target=\"_top\">Open verified view</a>",
            publication.publication_digest
        )
    } else {
        format!("<a href=\"capsule/capsule.json\">Download evidence capsule</a><h2>Attribution</h2><ul>{credits}</ul><h2>Limitations</h2><ul>{limitations}</ul>")
    };
    format!(
        r#"<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><style>body{{margin:0;background:#0b151a;color:#e8f2f1;font:15px system-ui,sans-serif}}main{{max-width:1000px;margin:auto;padding:20px}}img{{display:block;width:100%;height:auto;background:#fff;border-radius:8px}}.meta{{font-family:ui-monospace,monospace;font-size:12px;overflow-wrap:anywhere;color:#9fc0bd}}a{{color:#65e3c2}}</style></head><body><main><h1>{title}</h1><p>{description}</p><img alt="Verified spatial result" src="data:image/png;base64,{image}"><p class="meta">Result {result}<br>Workflow {workflow}<br>Publication {publication}</p>{evidence}</main></body></html>"#,
        title = escape(&publication.title),
        description = escape(&publication.description),
        image = BASE64.encode(png),
        result = escape(&publication.result_digest),
        workflow = escape(&publication.workflow_digest),
        publication = escape(&publication.publication_digest),
    )
}

fn copy_capsule(
    source: &Path,
    output: &Path,
    manifest: &CapsuleManifest,
) -> Result<(), CapsuleError> {
    let target = output.join("capsule");
    fs::create_dir_all(&target).map_err(|source_error| io_error(&target, source_error))?;
    for relative in std::iter::once("capsule.json")
        .chain(manifest.entries.iter().map(|entry| entry.path.as_str()))
    {
        validate_public_path(relative)?;
        let bytes = read_bytes(&source.join(relative))?;
        let destination = target.join(relative);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent).map_err(|source_error| io_error(parent, source_error))?;
        }
        fs::write(&destination, bytes)
            .map_err(|source_error| io_error(&destination, source_error))?;
    }
    Ok(())
}

fn validate_policy(policy: &PublicationPolicy) -> Result<(), CapsuleError> {
    if !policy.include_capsule_download
        || !policy.reject_local_paths
        || policy.included_field_classes.is_empty()
        || policy.redacted_field_classes.is_empty()
    {
        return Err(verify_error("publication policy weakens required M5 gates"));
    }
    Ok(())
}

fn contains_local_path(bytes: &[u8]) -> bool {
    let raw = String::from_utf8_lossy(bytes);
    let mut visible = String::with_capacity(raw.len());
    let mut remainder = raw.as_ref();
    while let Some(marker) = remainder.find("data:image/png;base64,") {
        visible.push_str(&remainder[..marker]);
        let encoded = &remainder[marker..];
        if let Some(end) = encoded.find('"') {
            remainder = &encoded[end + 1..];
        } else {
            remainder = "";
            break;
        }
    }
    visible.push_str(remainder);
    let text = visible.to_ascii_lowercase();
    if text.contains("file://") || text.contains("\\\\?\\") {
        return true;
    }
    let bytes = text.as_bytes();
    bytes.iter().enumerate().any(|(index, byte)| {
        if !byte.is_ascii_alphabetic()
            || bytes.get(index + 1) != Some(&b':')
            || !matches!(bytes.get(index + 2), Some(b'\\' | b'/'))
        {
            return false;
        }
        index == 0
            || matches!(
                bytes[index - 1],
                b' ' | b'\t' | b'\r' | b'\n' | b'"' | b'\'' | b'(' | b'=' | b'>'
            )
    })
}

fn validate_public_path(value: &str) -> Result<(), CapsuleError> {
    let path = Path::new(value);
    if path.is_absolute()
        || path
            .components()
            .any(|component| !matches!(component, std::path::Component::Normal(_)))
    {
        return Err(verify_error(format!(
            "non-portable publication path: {value}"
        )));
    }
    Ok(())
}

fn write_public_file(
    root: &Path,
    path: &str,
    bytes: &[u8],
) -> Result<PublicationFileEntry, CapsuleError> {
    validate_public_path(path)?;
    fs::write(root.join(path), bytes).map_err(|source| io_error(&root.join(path), source))?;
    Ok(PublicationFileEntry {
        path: path.into(),
        sha256: sha256(bytes),
        bytes: bytes.len() as u64,
    })
}

fn ensure_empty_destination(root: &Path) -> Result<(), CapsuleError> {
    if root.exists()
        && fs::read_dir(root)
            .map_err(|source| io_error(root, source))?
            .next()
            .is_some()
    {
        return Err(verify_error(format!(
            "publication destination is not empty: {}",
            root.display()
        )));
    }
    Ok(())
}

fn read_bytes(path: &Path) -> Result<Vec<u8>, CapsuleError> {
    fs::read(path).map_err(|source| io_error(path, source))
}

fn read_json<T: serde::de::DeserializeOwned>(path: &Path) -> Result<T, CapsuleError> {
    Ok(serde_json::from_slice(&read_bytes(path)?)?)
}

fn escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

fn sha256(bytes: &[u8]) -> String {
    format!("sha256:{:x}", Sha256::digest(bytes))
}

fn io_error(path: &Path, source: std::io::Error) -> CapsuleError {
    CapsuleError::Io {
        path: PathBuf::from(path),
        source,
    }
}

fn verify_error(message: impl Into<String>) -> CapsuleError {
    CapsuleError::Verification(message.into())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exports_and_verifies_allowlisted_share_and_embed_views() {
        let result = genegis_analysis::run_ask_pipeline("名古屋市の人口密度を表示")
            .expect("north-star result");
        let temp = tempfile::tempdir().expect("temp");
        let capsule = temp.path().join("capsule-source");
        crate::seal_nagoya_capsule(&result, &capsule).expect("capsule");
        let output = temp.path().join("publication");
        let publication =
            export_portable_publication(&capsule, &output, &PublicationPolicy::default())
                .expect("publication");
        assert!(publication.publication_digest.starts_with("sha256:"));
        assert!(!publication.attribution.is_empty());
        assert!(!publication.limitations.is_empty());
        let verified = verify_portable_publication(&output).expect("verified publication");
        assert_eq!(
            verified.result_digest,
            result.execution_receipt.result_digest
        );

        fs::write(output.join("embed.html"), b"file:///C:/private/data").expect("tamper");
        assert!(verify_portable_publication(&output).is_err());
    }
}
